defmodule Dotuh.Repo.Migrations.AddAudioPathToMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :audio_path, :text
    end
  end

  def down do
    alter table(:messages) do
      remove :audio_path
    end
  end
end
