defmodule Dotuh.Repo.Migrations.RemoveActiveColumn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:games) do
      remove :active
    end
  end

  def down do
    alter table(:games) do
      add :active, :boolean, default: true
    end
  end
end
