defmodule Dotuh.Repo.Migrations.AddEventIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:events, [:game_id, :game_time, :player_id],
             name: "events_unique_event_index"
           )
  end

  def down do
    drop_if_exists unique_index(:events, [:game_id, :game_time, :player_id],
                     name: "events_unique_event_index"
                   )
  end
end
