defmodule Dotuh.Repo.Migrations.AddTeamToHeroes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:heroes) do
      add :team, :text
    end
  end

  def down do
    alter table(:heroes) do
      remove :team
    end
  end
end
